
DROP TABLE IF EXISTS STUDENT_COURSE CASCADE;
DROP TABLE IF EXISTS STUDENT CASCADE;
DROP TABLE IF EXISTS COURSE CASCADE;

CREATE TABLE STUDENT (
--	STUDENT_ID uuid NOT NULL DEFAULT random_uuid(),
    STUDENT_ID uuid NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	AGE INT NOT NULL,
	PRIMARY KEY(STUDENT_ID)
);

CREATE TABLE COURSE (
--	COURSE_ID uuid NOT NULL DEFAULT random_uuid(),
    COURSE_ID uuid NOT NULL,
	DESCRIPTION VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY(COURSE_ID)
);

CREATE TABLE STUDENT_COURSE (
	STUDENT_ID uuid NOT NULL,
	COURSE_ID uuid NOT NULL,
	ENROLLED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT fk_COURSE FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID) ON UPDATE CASCADE ON DELETE CASCADE
);
